# .github/workflows/build.yml
name: build-and-push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Sanity-check the required secrets exist
      - name: Check required secrets
        run: |
          [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ] || { echo "Missing DOCKERHUB_USERNAME"; exit 1; }
          [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]    || { echo "Missing DOCKERHUB_TOKEN"; exit 1; }

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      # ✅ Login to Docker Hub (so push works)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # e.g. kermatron
          password: ${{ secrets.DOCKERHUB_TOKEN }}      # dckr_pat_...

      # Optional: clearer logs
      - name: Set buildx output to plain
        run: echo "BUILDKIT_PROGRESS=plain" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64            # required for CUDA wheels
          tags: kermatron/comfystuff:latest # adjust if you want extra tags
          provenance: false
          sbom: false
