name: build-and-push
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check required secrets
        run: |
          [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ] || { echo "Missing DOCKERHUB_USERNAME secret"; exit 1; }
          [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]    || { echo "Missing DOCKERHUB_TOKEN secret"; exit 1; }

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: kermatron/comfystuff:latest
