# .github/workflows/build.yml
name: build-and-push

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"   # e.g. v6, v6.1, v6.1.0
  workflow_dispatch:
    inputs:
      version:
        description: "Optional version tag to publish (e.g. v6)"
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      IMAGE_REPO: kermatron/comfystuff

    steps:
      - uses: actions/checkout@v4

      # Free disk space BEFORE the build
      - name: Free disk space (safe)
        shell: bash
        run: |
          echo "Disk before cleanup:" && df -h
          docker system prune -af || true
          docker volume prune -f || true
          docker builder prune -af || true
          echo "Disk after cleanup:" && df -h

      - name: Check required secrets
        shell: bash
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          : "${DOCKERHUB_USERNAME:?Missing DOCKERHUB_USERNAME}"
          : "${DOCKERHUB_TOKEN:?Missing DOCKERHUB_TOKEN}"

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_REPO }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ github.event.inputs.version }},enable=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version != '' }}

      - name: Show computed tags
        run: |
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "Labels: ${{ steps.meta.outputs.labels }}"

      # Build AND push in one step (best for disk usage)
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Use GHA cache but keep it small to avoid bloat
          cache-from: type=gha
          cache-to: type=gha,mode=min
          provenance: false
          sbom: false

      # Drop any leftover builder cache on the runner
      - name: Clean builder cache (post-build)
        if: always()
        run: |
          docker builder prune -af || true
          docker system df
