name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Clean up disk space on the GitHub runner
      - name: Free disk space
        run: |
          echo "Disk space before cleanup:"
          df -h
          sudo docker system prune -af || true
          sudo docker volume prune -f || true
          sudo rm -rf /opt/hostedtoolcache || true
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
          echo "Disk space after cleanup:"
          df -h

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-image:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-image:latest
